# Generated by Django 2.2.5 on 2020-07-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='projects',
            name='git',
            field=models.URLField(default=None, max_length=250),
        ),
    ]
